### ISSUE TITLE
ci: exercise tests are failing

### ISSUE THREAD

**Issue by ee7** [exercism/zig#104]
We can't merge #101 due to the [failing tests](https://github.com/exercism/zig/runs/7829052701).

The cause appears to be https://github.com/exercism/zig/pull/91, which claims to make the tests work on 0.8.1. But the CI currently runs on 0.7.0.

Currently failing tests in CI:

>````
>Running tests for binary_search
>./test_binary_search.zig:8:37: error: expected error union type, found 'void'
>    comptime try testing.expectEqual(0,
>                                    ^
>./test_binary_search.zig:8:14: note: referenced here
>    comptime try testing.expectEqual(0,
>             ^
>./test_binary_search.zig:14:37: error: expected error union type, found 'void'
>    comptime try testing.expectEqual(3,
>                                    ^
>./test_binary_search.zig:14:14: note: referenced here
>    comptime try testing.expectEqual(3,
>             ^
>./test_binary_search.zig:20:37: error: expected error union type, found 'void'
>    comptime try testing.expectEqual(0,
>                                    ^
>./test_binary_search.zig:20:14: note: referenced here
>    comptime try testing.expectEqual(0,
>             ^
>./test_binary_search.zig:26:37: error: expected error union type, found 'void'
>    comptime try testing.expectEqual(6,
>                                    ^
>./test_binary_search.zig:26:14: note: referenced here
>    comptime try testing.expectEqual(6,
>             ^
>./test_binary_search.zig:32:37: error: expected error union type, found 'void'
>    comptime try testing.expectEqual(5,
>                                    ^
>./test_binary_search.zig:32:14: note: referenced here
>    comptime try testing.expectEqual(5,
>             ^
>./test_binary_search.zig:38:37: error: expected error union type, found 'void'
>    comptime try testing.expectEqual(5,
>                                    ^
>./test_binary_search.zig:38:14: note: referenced here
>    comptime try testing.expectEqual(5,
>             ^
>./test_binary_search.zig:44:28: error: expected error union type, found 'void'
>    try testing.expectError(SearchError.ValueAbsent,
>                           ^
>./test_binary_search.zig:44:5: note: referenced here
>    try testing.expectError(SearchError.ValueAbsent,
>    ^
>./test_binary_search.zig:50:28: error: expected error union type, found 'void'
>    try testing.expectError(SearchError.ValueAbsent,
>                           ^
>./test_binary_search.zig:50:5: note: referenced here
>    try testing.expectError(SearchError.ValueAbsent,
>    ^
>./test_binary_search.zig:56:28: error: expected error union type, found 'void'
>    try testing.expectError(SearchError.ValueAbsent,
>                           ^
>./test_binary_search.zig:56:5: note: referenced here
>    try testing.expectError(SearchError.ValueAbsent,
>    ^
>./test_binary_search.zig:62:28: error: expected error union type, found 'void'
>    try testing.expectError(SearchError.EmptyBuffer,
>                           ^
>./test_binary_search.zig:62:5: note: referenced here
>    try testing.expectError(SearchError.EmptyBuffer,
>    ^
>./test_binary_search.zig:68:28: error: expected error union type, found 'void'
>    try testing.expectError(SearchError.ValueAbsent,
>                           ^
>./test_binary_search.zig:68:5: note: referenced here
>    try testing.expectError(SearchError.ValueAbsent,
>    ^
>````
